name: 'JetBrains ReSharper InspectCode'
description: 'C# static analysis using JetBrains ReSharper command line tools'
inputs:
  solution:
    description: 'solutiuon file'
    required: true
  dotnet-version:
    required: false
    description: '.NET SDK version'
  resharper-version:
    description: 'ReSharper version'
    required: true
    default: '2023.1.0'
    
runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install ReSharper command line tools
      shell: bash
      run: |
        dotnet tool install JetBrains.ReSharper.GlobalTools --global --version ${{ inputs.resharper-version }}

    - name: Inspect code with ReSharper
      shell: bash
      run: >
        jb inspectcode ${{ inputs.solution }}
        --output=results.sarif.json
        --format=Sarif
        --build

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif.json
        category: resharper-inspectcode
